<script>
	import * as Icon from '$lib';
</script>

<Icon.A360 size="30" variation="solid" />
<Icon.AbTesting size="30" variation="solid" />
<Icon.Add size="30" variation="solid" />
<Icon.AddSmall size="30" variation="solid" />
<Icon.AddressBook size="30" variation="solid" />
<Icon.AdjustHorizontal size="30" variation="solid" />
<Icon.AdjustHorizontalAlt size="30" variation="solid" />
<Icon.AdjustVertical size="30" variation="solid" />
<Icon.AdjustVerticalAlt size="30" variation="solid" />
<Icon.Airplay size="30" variation="solid" />
<Icon.Airpods size="30" variation="solid" />
<Icon.Alarm size="30" variation="solid" />
<Icon.Alien size="30" variation="solid" />
<Icon.AlignBottom size="30" variation="solid" />
<Icon.AlignCenterHorizontal size="30" variation="solid" />
<Icon.AlignCenterVertical size="30" variation="solid" />
<Icon.AlignLeft size="30" variation="solid" />
<Icon.AlignRight size="30" variation="solid" />
<Icon.AlignTextCenter size="30" variation="solid" />
<Icon.AlignTextJustify size="30" variation="solid" />
<Icon.AlignTextLeft size="30" variation="solid" />
<Icon.AlignTextRight size="30" variation="solid" />
<Icon.AlignTop size="30" variation="solid" />
<Icon.Anchor size="30" variation="solid" />
<Icon.Android size="30" variation="solid" />
<Icon.Angular size="30" variation="solid" />
<Icon.Anja size="30" variation="solid" />
<Icon.AntiClockwise size="30" variation="solid" />
<Icon.Apple size="30" variation="solid" />
<Icon.Appointments size="30" variation="solid" />
<Icon.Archive size="30" variation="solid" />
<Icon.AreaChart size="30" variation="solid" />
<Icon.AreaChartAlt size="30" variation="solid" />
<Icon.Arrow size="30" variation="solid" />
<Icon.ArrowDown size="30" variation="solid" />
<Icon.ArrowDownCircle size="30" variation="solid" />
<Icon.ArrowDownSmall size="30" variation="solid" />
<Icon.ArrowLeft size="30" variation="solid" />
<Icon.ArrowLeftCircle size="30" variation="solid" />
<Icon.ArrowLeftSmall size="30" variation="solid" />
<Icon.ArrowRight size="30" variation="solid" />
<Icon.ArrowRightCircle size="30" variation="solid" />
<Icon.ArrowRightSmall size="30" variation="solid" />
<Icon.ArrowUp size="30" variation="solid" />
<Icon.ArrowUpCircle size="30" variation="solid" />
<Icon.ArrowUpSmall size="30" variation="solid" />
<Icon.Artboard size="30" variation="solid" />
<Icon.At size="30" variation="solid" />
<Icon.Attach size="30" variation="solid" />
<Icon.Attachment size="30" variation="solid" />
<Icon.AudioCable size="30" variation="solid" />
<Icon.AudioDocument size="30" variation="solid" />
<Icon.Azure size="30" variation="solid" />
<Icon.Backspace size="30" variation="solid" />
<Icon.Bag size="30" variation="solid" />
<Icon.BagAlt size="30" variation="solid" />
<Icon.BagMinus size="30" variation="solid" />
<Icon.BagPlus size="30" variation="solid" />
<Icon.Bank size="30" variation="solid" />
<Icon.BarChart size="30" variation="solid" />
<Icon.Barcode size="30" variation="solid" />
<Icon.Basket size="30" variation="solid" />
<Icon.BasketMinus size="30" variation="solid" />
<Icon.BasketPlus size="30" variation="solid" />
<Icon.Bath size="30" variation="solid" />
<Icon.Battery0 size="30" variation="solid" />
<Icon.Battery1 size="30" variation="solid" />
<Icon.Battery2 size="30" variation="solid" />
<Icon.Battery3 size="30" variation="solid" />
<Icon.Battery4 size="30" variation="solid" />
<Icon.Battery5 size="30" variation="solid" />
<Icon.BatteryCharge size="30" variation="solid" />
<Icon.BedDouble size="30" variation="solid" />
<Icon.BedSingle size="30" variation="solid" />
<Icon.Behance size="30" variation="solid" />
<Icon.Bell size="30" variation="solid" />
<Icon.Bin size="30" variation="solid" />
<Icon.Bitbucket size="30" variation="solid" />
<Icon.Bitcoin size="30" variation="solid" />
<Icon.Bluetooth size="30" variation="solid" />
<Icon.Bold size="30" variation="solid" />
<Icon.Book size="30" variation="solid" />
<Icon.Bookmark size="30" variation="solid" />
<Icon.BorderAll size="30" variation="solid" />
<Icon.BorderBottom size="30" variation="solid" />
<Icon.BorderHorizontal size="30" variation="solid" />
<Icon.BorderInner size="30" variation="solid" />
<Icon.BorderLeft size="30" variation="solid" />
<Icon.BorderNone size="30" variation="solid" />
<Icon.BorderOuter size="30" variation="solid" />
<Icon.BorderRadius size="30" variation="solid" />
<Icon.BorderRight size="30" variation="solid" />
<Icon.BorderTop size="30" variation="solid" />
<Icon.BorderVertical size="30" variation="solid" />
<Icon.BottomLeft size="30" variation="solid" />
<Icon.BottomRight size="30" variation="solid" />
<Icon.Box size="30" variation="solid" />
<Icon.Bracket size="30" variation="solid" />
<Icon.Briefcase size="30" variation="solid" />
<Icon.BriefcaseAlt size="30" variation="solid" />
<Icon.Brush size="30" variation="solid" />
<Icon.Bug size="30" variation="solid" />
<Icon.Building size="30" variation="solid" />
<Icon.BulbOff size="30" variation="solid" />
<Icon.BulbOn size="30" variation="solid" />
<Icon.Button size="30" variation="solid" />
<Icon.C size="30" variation="solid" />
<Icon.CSharp size="30" variation="solid" />
<Icon.Calculator size="30" variation="solid" />
<Icon.Calendar size="30" variation="solid" />
<Icon.CalendarMinus size="30" variation="solid" />
<Icon.CalendarNoAccess size="30" variation="solid" />
<Icon.CalendarPlus size="30" variation="solid" />
<Icon.CalendarTick size="30" variation="solid" />
<Icon.CalendarX size="30" variation="solid" />
<Icon.Camera size="30" variation="solid" />
<Icon.CandleChart size="30" variation="solid" />
<Icon.Car size="30" variation="solid" />
<Icon.CaretVertical size="30" variation="solid" />
<Icon.CaretVerticalCircle size="30" variation="solid" />
<Icon.CaretVerticalSmall size="30" variation="solid" />
<Icon.Cart size="30" variation="solid" />
<Icon.CartMinus size="30" variation="solid" />
<Icon.CartPlus size="30" variation="solid" />
<Icon.Certificate size="30" variation="solid" />
<Icon.Chat size="30" variation="solid" />
<Icon.ChatTyping size="30" variation="solid" />
<Icon.ChatTypingAlt size="30" variation="solid" />
<Icon.Chatbot size="30" variation="solid" />
<Icon.Chrome size="30" variation="solid" />
<Icon.Church size="30" variation="solid" />
<Icon.Circle size="30" variation="solid" />
<Icon.Clipboard size="30" variation="solid" />
<Icon.ClipboardMinus size="30" variation="solid" />
<Icon.ClipboardNoAccess size="30" variation="solid" />
<Icon.ClipboardPlus size="30" variation="solid" />
<Icon.ClipboardTick size="30" variation="solid" />
<Icon.ClipboardX size="30" variation="solid" />
<Icon.Clock size="30" variation="solid" />
<Icon.Clockwise size="30" variation="solid" />
<Icon.Code size="30" variation="solid" />
<Icon.Codepen size="30" variation="solid" />
<Icon.Cog size="30" variation="solid" />
<Icon.Compass size="30" variation="solid" />
<Icon.Computer size="30" variation="solid" />
<Icon.Contact size="30" variation="solid" />
<Icon.Contract size="30" variation="solid" />
<Icon.CostEstimate size="30" variation="solid" />
<Icon.Cplusplus size="30" variation="solid" />
<Icon.CreditCard size="30" variation="solid" />
<Icon.Crop size="30" variation="solid" />
<Icon.Css3 size="30" variation="solid" />
<Icon.Csv size="30" variation="solid" />
<Icon.Cup size="30" variation="solid" />
<Icon.CurvedConnector size="30" variation="solid" />
<Icon.D3 size="30" variation="solid" />
<Icon.Database size="30" variation="solid" />
<Icon.Denied size="30" variation="solid" />
<Icon.Deno size="30" variation="solid" />
<Icon.DepthChart size="30" variation="solid" />
<Icon.Desklamp size="30" variation="solid" />
<Icon.Diamond size="30" variation="solid" />
<Icon.Direction size="30" variation="solid" />
<Icon.Discord size="30" variation="solid" />
<Icon.Discount size="30" variation="solid" />
<Icon.DistributeHorizontal size="30" variation="solid" />
<Icon.DistributeVertical size="30" variation="solid" />
<Icon.DividerLine size="30" variation="solid" />
<Icon.Doc size="30" variation="solid" />
<Icon.Docker size="30" variation="solid" />
<Icon.Documents size="30" variation="solid" />
<Icon.Dollar size="30" variation="solid" />
<Icon.DonutChart size="30" variation="solid" />
<Icon.DoubleCaretDown size="30" variation="solid" />
<Icon.DoubleCaretDownCircle size="30" variation="solid" />
<Icon.DoubleCaretDownSmall size="30" variation="solid" />
<Icon.DoubleCaretLeft size="30" variation="solid" />
<Icon.DoubleCaretLeftCircle size="30" variation="solid" />
<Icon.DoubleCaretLeftSmall size="30" variation="solid" />
<Icon.DoubleCaretRight size="30" variation="solid" />
<Icon.DoubleCaretRightCircle size="30" variation="solid" />
<Icon.DoubleCaretRightSmall size="30" variation="solid" />
<Icon.DoubleCaretUp size="30" variation="solid" />
<Icon.DoubleCaretUpCircle size="30" variation="solid" />
<Icon.DoubleCaretUpSmall size="30" variation="solid" />
<Icon.Down size="30" variation="solid" />
<Icon.DownCircle size="30" variation="solid" />
<Icon.DownSmall size="30" variation="solid" />
<Icon.Download size="30" variation="solid" />
<Icon.Drag size="30" variation="solid" />
<Icon.DragHorizontal size="30" variation="solid" />
<Icon.DragVertical size="30" variation="solid" />
<Icon.Dribbble size="30" variation="solid" />
<Icon.Drop size="30" variation="solid" />
<Icon.Dropper size="30" variation="solid" />
<Icon.Edge size="30" variation="solid" />
<Icon.Edit size="30" variation="solid" />
<Icon.Edit1 size="30" variation="solid" />
<Icon.EditCircle size="30" variation="solid" />
<Icon.EditSmall size="30" variation="solid" />
<Icon.ElbowConnector size="30" variation="solid" />
<Icon.Envelope size="30" variation="solid" />
<Icon.EnvelopeOpen size="30" variation="solid" />
<Icon.Eps size="30" variation="solid" />
<Icon.Eslint size="30" variation="solid" />
<Icon.Ethereum size="30" variation="solid" />
<Icon.Euro size="30" variation="solid" />
<Icon.Exclamation size="30" variation="solid" />
<Icon.ExclamationCircle size="30" variation="solid" />
<Icon.ExclamationSmall size="30" variation="solid" />
<Icon.Expand size="30" variation="solid" />
<Icon.ExpandAlt size="30" variation="solid" />
<Icon.Eye size="30" variation="solid" />
<Icon.EyeClosed size="30" variation="solid" />
<Icon.FaceId size="30" variation="solid" />
<Icon.Facebook size="30" variation="solid" />
<Icon.Figma size="30" variation="solid" />
<Icon.File size="30" variation="solid" />
<Icon.FileMinus size="30" variation="solid" />
<Icon.FileNoAccess size="30" variation="solid" />
<Icon.FilePlus size="30" variation="solid" />
<Icon.FileTick size="30" variation="solid" />
<Icon.FileX size="30" variation="solid" />
<Icon.Filter size="30" variation="solid" />
<Icon.Fingerprint size="30" variation="solid" />
<Icon.Firebase size="30" variation="solid" />
<Icon.Flag size="30" variation="solid" />
<Icon.FlagAlt size="30" variation="solid" />
<Icon.FlipHorizontal size="30" variation="solid" />
<Icon.FlipVertical size="30" variation="solid" />
<Icon.FloatCenter size="30" variation="solid" />
<Icon.FloatLeft size="30" variation="solid" />
<Icon.FloatRight size="30" variation="solid" />
<Icon.Floorplan size="30" variation="solid" />
<Icon.Folder size="30" variation="solid" />
<Icon.FolderMinus size="30" variation="solid" />
<Icon.FolderNoAccess size="30" variation="solid" />
<Icon.FolderPlus size="30" variation="solid" />
<Icon.FolderTick size="30" variation="solid" />
<Icon.FolderX size="30" variation="solid" />
<Icon.Folders size="30" variation="solid" />
<Icon.Forward size="30" variation="solid" />
<Icon.ForwardCircle size="30" variation="solid" />
<Icon.ForwardSmall size="30" variation="solid" />
<Icon.Frame size="30" variation="solid" />
<Icon.Framer size="30" variation="solid" />
<Icon.GameController size="30" variation="solid" />
<Icon.GameControllerRetro size="30" variation="solid" />
<Icon.GanttChart size="30" variation="solid" />
<Icon.Garage size="30" variation="solid" />
<Icon.Gatsbyjs size="30" variation="solid" />
<Icon.Gba size="30" variation="solid" />
<Icon.Gbc size="30" variation="solid" />
<Icon.Ghost size="30" variation="solid" />
<Icon.Gif size="30" variation="solid" />
<Icon.Gift size="30" variation="solid" />
<Icon.Git size="30" variation="solid" />
<Icon.GitBranch size="30" variation="solid" />
<Icon.GitCommit size="30" variation="solid" />
<Icon.GitCompare size="30" variation="solid" />
<Icon.GitFork size="30" variation="solid" />
<Icon.GitMerge size="30" variation="solid" />
<Icon.GitPull size="30" variation="solid" />
<Icon.Github size="30" variation="solid" />
<Icon.Gitlab size="30" variation="solid" />
<Icon.Globe size="30" variation="solid" />
<Icon.GlobeAfrica size="30" variation="solid" />
<Icon.GlobeAmericas size="30" variation="solid" />
<Icon.Google size="30" variation="solid" />
<Icon.GoogleAd size="30" variation="solid" />
<Icon.GoogleDrive size="30" variation="solid" />
<Icon.GooglePlayStore size="30" variation="solid" />
<Icon.GoogleStreetview size="30" variation="solid" />
<Icon.Graphql size="30" variation="solid" />
<Icon.GridLayout size="30" variation="solid" />
<Icon.Hashtag size="30" variation="solid" />
<Icon.HdScreen size="30" variation="solid" />
<Icon.HdmiCable size="30" variation="solid" />
<Icon.Headphones size="30" variation="solid" />
<Icon.Headset size="30" variation="solid" />
<Icon.Heart size="30" variation="solid" />
<Icon.HeartCircle size="30" variation="solid" />
<Icon.HeartSmall size="30" variation="solid" />
<Icon.Hexagon size="30" variation="solid" />
<Icon.History size="30" variation="solid" />
<Icon.Home size="30" variation="solid" />
<Icon.HomeAlt size="30" variation="solid" />
<Icon.Hospital size="30" variation="solid" />
<Icon.Hourglass size="30" variation="solid" />
<Icon.House size="30" variation="solid" />
<Icon.Html5 size="30" variation="solid" />
<Icon.Id size="30" variation="solid" />
<Icon.Imac size="30" variation="solid" />
<Icon.Image size="30" variation="solid" />
<Icon.ImageAlt size="30" variation="solid" />
<Icon.ImageDocument size="30" variation="solid" />
<Icon.InEarHeadphones size="30" variation="solid" />
<Icon.Inbox size="30" variation="solid" />
<Icon.IndentDecrease size="30" variation="solid" />
<Icon.IndentIncrease size="30" variation="solid" />
<Icon.Info size="30" variation="solid" />
<Icon.InfoCircle size="30" variation="solid" />
<Icon.InfoSmall size="30" variation="solid" />
<Icon.Instagram size="30" variation="solid" />
<Icon.Invoice size="30" variation="solid" />
<Icon.Italic size="30" variation="solid" />
<Icon.Javascript size="30" variation="solid" />
<Icon.Joystick size="30" variation="solid" />
<Icon.Jpg size="30" variation="solid" />
<Icon.Kanban size="30" variation="solid" />
<Icon.Key size="30" variation="solid" />
<Icon.Keyboard size="30" variation="solid" />
<Icon.LanCable size="30" variation="solid" />
<Icon.Laptop size="30" variation="solid" />
<Icon.Laravel size="30" variation="solid" />
<Icon.Layers size="30" variation="solid" />
<Icon.LayersDifference size="30" variation="solid" />
<Icon.LayersIntersect size="30" variation="solid" />
<Icon.LayersSubtract size="30" variation="solid" />
<Icon.LayersUnion size="30" variation="solid" />
<Icon.Left size="30" variation="solid" />
<Icon.LeftCircle size="30" variation="solid" />
<Icon.LeftSmall size="30" variation="solid" />
<Icon.Lego size="30" variation="solid" />
<Icon.Lifebuoy size="30" variation="solid" />
<Icon.LightningCable size="30" variation="solid" />
<Icon.Line size="30" variation="solid" />
<Icon.Link size="30" variation="solid" />
<Icon.LinkRemove size="30" variation="solid" />
<Icon.Linkedin size="30" variation="solid" />
<Icon.Linux size="30" variation="solid" />
<Icon.LinuxAlt size="30" variation="solid" />
<Icon.ListLayout size="30" variation="solid" />
<Icon.ListOrdered size="30" variation="solid" />
<Icon.ListUnordered size="30" variation="solid" />
<Icon.Litecoin size="30" variation="solid" />
<Icon.Loader size="30" variation="solid" />
<Icon.Location size="30" variation="solid" />
<Icon.Lock size="30" variation="solid" />
<Icon.LockCircle size="30" variation="solid" />
<Icon.LockSmall size="30" variation="solid" />
<Icon.Logout size="30" variation="solid" />
<Icon.Loop size="30" variation="solid" />
<Icon.Magsafe size="30" variation="solid" />
<Icon.Markdown size="30" variation="solid" />
<Icon.Medium size="30" variation="solid" />
<Icon.Menu size="30" variation="solid" />
<Icon.Message size="30" variation="solid" />
<Icon.MessageMinus size="30" variation="solid" />
<Icon.MessageNoAccess size="30" variation="solid" />
<Icon.MessagePlus size="30" variation="solid" />
<Icon.MessageText size="30" variation="solid" />
<Icon.MessageTextAlt size="30" variation="solid" />
<Icon.MessageTick size="30" variation="solid" />
<Icon.MessageX size="30" variation="solid" />
<Icon.Messenger size="30" variation="solid" />
<Icon.MicroSdCard size="30" variation="solid" />
<Icon.Microphone size="30" variation="solid" />
<Icon.Minimise size="30" variation="solid" />
<Icon.MinimiseAlt size="30" variation="solid" />
<Icon.Minus size="30" variation="solid" />
<Icon.MinusCircle size="30" variation="solid" />
<Icon.MinusSmall size="30" variation="solid" />
<Icon.Mobile size="30" variation="solid" />
<Icon.Money size="30" variation="solid" />
<Icon.MoneyStack size="30" variation="solid" />
<Icon.Mongodb size="30" variation="solid" />
<Icon.MoodFlat size="30" variation="solid" />
<Icon.MoodFrown size="30" variation="solid" />
<Icon.MoodLaugh size="30" variation="solid" />
<Icon.MoodSad size="30" variation="solid" />
<Icon.MoodSmile size="30" variation="solid" />
<Icon.MoodSurprised size="30" variation="solid" />
<Icon.MoodTongue size="30" variation="solid" />
<Icon.Moon size="30" variation="solid" />
<Icon.MoreHorizontal size="30" variation="solid" />
<Icon.MoreVertical size="30" variation="solid" />
<Icon.Mouse size="30" variation="solid" />
<Icon.Mov size="30" variation="solid" />
<Icon.Mp3 size="30" variation="solid" />
<Icon.Mp4 size="30" variation="solid" />
<Icon.MsExcel size="30" variation="solid" />
<Icon.MsPowerpoint size="30" variation="solid" />
<Icon.MsWord size="30" variation="solid" />
<Icon.N64 size="30" variation="solid" />
<Icon.Nes size="30" variation="solid" />
<Icon.Netlify size="30" variation="solid" />
<Icon.Next size="30" variation="solid" />
<Icon.NextCircle size="30" variation="solid" />
<Icon.NextSmall size="30" variation="solid" />
<Icon.Nextjs size="30" variation="solid" />
<Icon.Ngc size="30" variation="solid" />
<Icon.NintendoSwitch size="30" variation="solid" />
<Icon.Nodejs size="30" variation="solid" />
<Icon.Note size="30" variation="solid" />
<Icon.Npm size="30" variation="solid" />
<Icon.Nuxtjs size="30" variation="solid" />
<Icon.Omega size="30" variation="solid" />
<Icon.Opera size="30" variation="solid" />
<Icon.Otp size="30" variation="solid" />
<Icon.PageBreak size="30" variation="solid" />
<Icon.PageNumber size="30" variation="solid" />
<Icon.Paintbrush size="30" variation="solid" />
<Icon.Paintbucket size="30" variation="solid" />
<Icon.Paragraph size="30" variation="solid" />
<Icon.Password size="30" variation="solid" />
<Icon.Patreon size="30" variation="solid" />
<Icon.Pause size="30" variation="solid" />
<Icon.PauseCircle size="30" variation="solid" />
<Icon.PauseSmall size="30" variation="solid" />
<Icon.Paw size="30" variation="solid" />
<Icon.Paws size="30" variation="solid" />
<Icon.Paypal size="30" variation="solid" />
<Icon.Pdf size="30" variation="solid" />
<Icon.Pen size="30" variation="solid" />
<Icon.Phone size="30" variation="solid" />
<Icon.Phonecall size="30" variation="solid" />
<Icon.PhonecallBlocked size="30" variation="solid" />
<Icon.PhonecallReceive size="30" variation="solid" />
<Icon.PieChart size="30" variation="solid" />
<Icon.PieChartAlt size="30" variation="solid" />
<Icon.Pin size="30" variation="solid" />
<Icon.PinAlt size="30" variation="solid" />
<Icon.Pinterest size="30" variation="solid" />
<Icon.Plant size="30" variation="solid" />
<Icon.Play size="30" variation="solid" />
<Icon.PlayCircle size="30" variation="solid" />
<Icon.PlaySmall size="30" variation="solid" />
<Icon.Plug size="30" variation="solid" />
<Icon.PlusCircle size="30" variation="solid" />
<Icon.Png size="30" variation="solid" />
<Icon.Pool size="30" variation="solid" />
<Icon.Pound size="30" variation="solid" />
<Icon.Power size="30" variation="solid" />
<Icon.Ppt size="30" variation="solid" />
<Icon.Print size="30" variation="solid" />
<Icon.Python size="30" variation="solid" />
<Icon.QrCode size="30" variation="solid" />
<Icon.Question size="30" variation="solid" />
<Icon.QuestionCircle size="30" variation="solid" />
<Icon.QuestionSmall size="30" variation="solid" />
<Icon.Quote size="30" variation="solid" />
<Icon.Rand size="30" variation="solid" />
<Icon.React size="30" variation="solid" />
<Icon.Receipt size="30" variation="solid" />
<Icon.Reddit size="30" variation="solid" />
<Icon.Redwoodjs size="30" variation="solid" />
<Icon.Refresh size="30" variation="solid" />
<Icon.RefreshAlt size="30" variation="solid" />
<Icon.Rewind size="30" variation="solid" />
<Icon.RewindCircle size="30" variation="solid" />
<Icon.RewindSmall size="30" variation="solid" />
<Icon.Right size="30" variation="solid" />
<Icon.RightCircle size="30" variation="solid" />
<Icon.RightSmall size="30" variation="solid" />
<Icon.Ripple size="30" variation="solid" />
<Icon.Robot size="30" variation="solid" />
<Icon.Roller size="30" variation="solid" />
<Icon.Rollupjs size="30" variation="solid" />
<Icon.Router size="30" variation="solid" />
<Icon.Rss size="30" variation="solid" />
<Icon.Ruby size="30" variation="solid" />
<Icon.Rupee size="30" variation="solid" />
<Icon.Rust size="30" variation="solid" />
<Icon.Safari size="30" variation="solid" />
<Icon.Safe size="30" variation="solid" />
<Icon.Save size="30" variation="solid" />
<Icon.Scan size="30" variation="solid" />
<Icon.School size="30" variation="solid" />
<Icon.Screen size="30" variation="solid" />
<Icon.ScreenAlt size="30" variation="solid" />
<Icon.ScreenAlt2 size="30" variation="solid" />
<Icon.Scribble size="30" variation="solid" />
<Icon.SdCard size="30" variation="solid" />
<Icon.Search size="30" variation="solid" />
<Icon.SearchCircle size="30" variation="solid" />
<Icon.SearchProperty size="30" variation="solid" />
<Icon.SearchSmall size="30" variation="solid" />
<Icon.SectionAdd size="30" variation="solid" />
<Icon.SectionRemove size="30" variation="solid" />
<Icon.Send size="30" variation="solid" />
<Icon.SendDown size="30" variation="solid" />
<Icon.SendLeft size="30" variation="solid" />
<Icon.SendRight size="30" variation="solid" />
<Icon.SendUp size="30" variation="solid" />
<Icon.Servers size="30" variation="solid" />
<Icon.Share size="30" variation="solid" />
<Icon.Shield size="30" variation="solid" />
<Icon.ShieldTick size="30" variation="solid" />
<Icon.ShieldX size="30" variation="solid" />
<Icon.Shop size="30" variation="solid" />
<Icon.Sign size="30" variation="solid" />
<Icon.Signin size="30" variation="solid" />
<Icon.Sim size="30" variation="solid" />
<Icon.Simohamed size="30" variation="solid" />
<Icon.Skull size="30" variation="solid" />
<Icon.Skype size="30" variation="solid" />
<Icon.Slack size="30" variation="solid" />
<Icon.Snapchat size="30" variation="solid" />
<Icon.Snes size="30" variation="solid" />
<Icon.SortAlphabetically size="30" variation="solid" />
<Icon.SortDown size="30" variation="solid" />
<Icon.SortHighToLow size="30" variation="solid" />
<Icon.SortLowToHigh size="30" variation="solid" />
<Icon.SortReverseAlphabetically size="30" variation="solid" />
<Icon.SortUp size="30" variation="solid" />
<Icon.SoundOff size="30" variation="solid" />
<Icon.SoundOn size="30" variation="solid" />
<Icon.Spotify size="30" variation="solid" />
<Icon.Spreadsheet size="30" variation="solid" />
<Icon.Square size="30" variation="solid" />
<Icon.Stackoverflow size="30" variation="solid" />
<Icon.Stamp size="30" variation="solid" />
<Icon.Star size="30" variation="solid" />
<Icon.StarCircle size="30" variation="solid" />
<Icon.StarSmall size="30" variation="solid" />
<Icon.Stop size="30" variation="solid" />
<Icon.StopCircle size="30" variation="solid" />
<Icon.StopSmall size="30" variation="solid" />
<Icon.Stopwatch size="30" variation="solid" />
<Icon.Strikethrough size="30" variation="solid" />
<Icon.Subscript size="30" variation="solid" />
<Icon.Sun size="30" variation="solid" />
<Icon.Superscript size="30" variation="solid" />
<Icon.Svelte size="30" variation="solid" />
<Icon.Svg size="30" variation="solid" />
<Icon.Table size="30" variation="solid" />
<Icon.Tablet size="30" variation="solid" />
<Icon.Tag size="30" variation="solid" />
<Icon.Tailwind size="30" variation="solid" />
<Icon.Target size="30" variation="solid" />
<Icon.Telegram size="30" variation="solid" />
<Icon.Terminal size="30" variation="solid" />
<Icon.Text size="30" variation="solid" />
<Icon.TextDocument size="30" variation="solid" />
<Icon.TextDocumentAlt size="30" variation="solid" />
<Icon.ThumbDown size="30" variation="solid" />
<Icon.ThumbUp size="30" variation="solid" />
<Icon.Thumbtack size="30" variation="solid" />
<Icon.Tick size="30" variation="solid" />
<Icon.TickCircle size="30" variation="solid" />
<Icon.TickSmall size="30" variation="solid" />
<Icon.Tiktok size="30" variation="solid" />
<Icon.Toggle size="30" variation="solid" />
<Icon.TopLeft size="30" variation="solid" />
<Icon.TopRight size="30" variation="solid" />
<Icon.TrendDown size="30" variation="solid" />
<Icon.TrendUp size="30" variation="solid" />
<Icon.Triangle size="30" variation="solid" />
<Icon.Trophy size="30" variation="solid" />
<Icon.Tv size="30" variation="solid" />
<Icon.Twitch size="30" variation="solid" />
<Icon.Twitter size="30" variation="solid" />
<Icon.Typescript size="30" variation="solid" />
<Icon.Underline size="30" variation="solid" />
<Icon.Unlock size="30" variation="solid" />
<Icon.UnlockCircle size="30" variation="solid" />
<Icon.UnlockSmall size="30" variation="solid" />
<Icon.Up size="30" variation="solid" />
<Icon.UpCircle size="30" variation="solid" />
<Icon.UpSmall size="30" variation="solid" />
<Icon.Upload size="30" variation="solid" />
<Icon.UsbCable size="30" variation="solid" />
<Icon.User size="30" variation="solid" />
<Icon.UserCircle size="30" variation="solid" />
<Icon.UserMinus size="30" variation="solid" />
<Icon.UserPlus size="30" variation="solid" />
<Icon.UserSquare size="30" variation="solid" />
<Icon.Users size="30" variation="solid" />
<Icon.VectorDocument size="30" variation="solid" />
<Icon.VennDiagram size="30" variation="solid" />
<Icon.ViewColumn size="30" variation="solid" />
<Icon.ViewGrid size="30" variation="solid" />
<Icon.Vim size="30" variation="solid" />
<Icon.Volume1 size="30" variation="solid" />
<Icon.Volume2 size="30" variation="solid" />
<Icon.Volume3 size="30" variation="solid" />
<Icon.VrHeadset size="30" variation="solid" />
<Icon.Vue size="30" variation="solid" />
<Icon.Wallet size="30" variation="solid" />
<Icon.WalletAlt size="30" variation="solid" />
<Icon.Wan size="30" variation="solid" />
<Icon.Wand size="30" variation="solid" />
<Icon.Watch size="30" variation="solid" />
<Icon.Webpack size="30" variation="solid" />
<Icon.Whatsapp size="30" variation="solid" />
<Icon.WifiFull size="30" variation="solid" />
<Icon.WifiLow size="30" variation="solid" />
<Icon.WifiNone size="30" variation="solid" />
<Icon.Windows size="30" variation="solid" />
<Icon.Wordpress size="30" variation="solid" />
<Icon.X size="30" variation="solid" />
<Icon.XCircle size="30" variation="solid" />
<Icon.XSmall size="30" variation="solid" />
<Icon.Xls size="30" variation="solid" />
<Icon.Yen size="30" variation="solid" />
<Icon.Youtube size="30" variation="solid" />
<Icon.Zip size="30" variation="solid" />
<Icon.ZoomIn size="30" variation="solid" />
<Icon.ZoomOut size="30" variation="solid" />
