<script>
  import * as Icon from '$lib';
  const random_hex_color_code = () => {
    let n = (Math.random() * 0xfffff * 1000000).toString(16);
    return '#' + n.slice(0, 6);
  };
</script>

<Icon.A360 size="40" color={random_hex_color_code()} variation="solid" />
<Icon.AbTesting size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Add size="40" color={random_hex_color_code()} variation="solid" />
<Icon.AddSmall size="40" color={random_hex_color_code()} variation="solid" />
<Icon.AddressBook size="40" color={random_hex_color_code()} variation="solid" />
<Icon.AdjustHorizontal size="40" color={random_hex_color_code()} variation="solid" />
<Icon.AdjustHorizontalAlt size="40" color={random_hex_color_code()} variation="solid" />
<Icon.AdjustVertical size="40" color={random_hex_color_code()} variation="solid" />
<Icon.AdjustVerticalAlt size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Airplay size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Airpods size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Alarm size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Alien size="40" color={random_hex_color_code()} variation="solid" />
<Icon.AlignBottom size="40" color={random_hex_color_code()} variation="solid" />
<Icon.AlignCenterHorizontal size="40" color={random_hex_color_code()} variation="solid" />
<Icon.AlignCenterVertical size="40" color={random_hex_color_code()} variation="solid" />
<Icon.AlignLeft size="40" color={random_hex_color_code()} variation="solid" />
<Icon.AlignRight size="40" color={random_hex_color_code()} variation="solid" />
<Icon.AlignTextCenter size="40" color={random_hex_color_code()} variation="solid" />
<Icon.AlignTextJustify size="40" color={random_hex_color_code()} variation="solid" />
<Icon.AlignTextLeft size="40" color={random_hex_color_code()} variation="solid" />
<Icon.AlignTextRight size="40" color={random_hex_color_code()} variation="solid" />
<Icon.AlignTop size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Anchor size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Android size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Angular size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Anja size="40" color={random_hex_color_code()} variation="solid" />
<Icon.AntiClockwise size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Apple size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Appointments size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Archive size="40" color={random_hex_color_code()} variation="solid" />
<Icon.AreaChart size="40" color={random_hex_color_code()} variation="solid" />
<Icon.AreaChartAlt size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Arrow size="40" color={random_hex_color_code()} variation="solid" />
<Icon.ArrowDown size="40" color={random_hex_color_code()} variation="solid" />
<Icon.ArrowDownCircle size="40" color={random_hex_color_code()} variation="solid" />
<Icon.ArrowDownSmall size="40" color={random_hex_color_code()} variation="solid" />
<Icon.ArrowLeft size="40" color={random_hex_color_code()} variation="solid" />
<Icon.ArrowLeftCircle size="40" color={random_hex_color_code()} variation="solid" />
<Icon.ArrowLeftSmall size="40" color={random_hex_color_code()} variation="solid" />
<Icon.ArrowRight size="40" color={random_hex_color_code()} variation="solid" />
<Icon.ArrowRightCircle size="40" color={random_hex_color_code()} variation="solid" />
<Icon.ArrowRightSmall size="40" color={random_hex_color_code()} variation="solid" />
<Icon.ArrowUp size="40" color={random_hex_color_code()} variation="solid" />
<Icon.ArrowUpCircle size="40" color={random_hex_color_code()} variation="solid" />
<Icon.ArrowUpSmall size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Artboard size="40" color={random_hex_color_code()} variation="solid" />
<Icon.At size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Attach size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Attachment size="40" color={random_hex_color_code()} variation="solid" />
<Icon.AudioCable size="40" color={random_hex_color_code()} variation="solid" />
<Icon.AudioDocument size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Azure size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Backspace size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Bag size="40" color={random_hex_color_code()} variation="solid" />
<Icon.BagAlt size="40" color={random_hex_color_code()} variation="solid" />
<Icon.BagMinus size="40" color={random_hex_color_code()} variation="solid" />
<Icon.BagPlus size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Bank size="40" color={random_hex_color_code()} variation="solid" />
<Icon.BarChart size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Barcode size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Basket size="40" color={random_hex_color_code()} variation="solid" />
<Icon.BasketMinus size="40" color={random_hex_color_code()} variation="solid" />
<Icon.BasketPlus size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Bath size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Battery0 size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Battery1 size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Battery2 size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Battery3 size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Battery4 size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Battery5 size="40" color={random_hex_color_code()} variation="solid" />
<Icon.BatteryCharge size="40" color={random_hex_color_code()} variation="solid" />
<Icon.BedDouble size="40" color={random_hex_color_code()} variation="solid" />
<Icon.BedSingle size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Behance size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Bell size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Bin size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Bitbucket size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Bitcoin size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Bluetooth size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Bold size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Book size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Bookmark size="40" color={random_hex_color_code()} variation="solid" />
<Icon.BorderAll size="40" color={random_hex_color_code()} variation="solid" />
<Icon.BorderBottom size="40" color={random_hex_color_code()} variation="solid" />
<Icon.BorderHorizontal size="40" color={random_hex_color_code()} variation="solid" />
<Icon.BorderInner size="40" color={random_hex_color_code()} variation="solid" />
<Icon.BorderLeft size="40" color={random_hex_color_code()} variation="solid" />
<Icon.BorderNone size="40" color={random_hex_color_code()} variation="solid" />
<Icon.BorderOuter size="40" color={random_hex_color_code()} variation="solid" />
<Icon.BorderRadius size="40" color={random_hex_color_code()} variation="solid" />
<Icon.BorderRight size="40" color={random_hex_color_code()} variation="solid" />
<Icon.BorderTop size="40" color={random_hex_color_code()} variation="solid" />
<Icon.BorderVertical size="40" color={random_hex_color_code()} variation="solid" />
<Icon.BottomLeft size="40" color={random_hex_color_code()} variation="solid" />
<Icon.BottomRight size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Box size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Bracket size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Briefcase size="40" color={random_hex_color_code()} variation="solid" />
<Icon.BriefcaseAlt size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Brush size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Bug size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Building size="40" color={random_hex_color_code()} variation="solid" />
<Icon.BulbOff size="40" color={random_hex_color_code()} variation="solid" />
<Icon.BulbOn size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Button size="40" color={random_hex_color_code()} variation="solid" />
<Icon.C size="40" color={random_hex_color_code()} variation="solid" />
<Icon.CSharp size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Calculator size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Calendar size="40" color={random_hex_color_code()} variation="solid" />
<Icon.CalendarMinus size="40" color={random_hex_color_code()} variation="solid" />
<Icon.CalendarNoAccess size="40" color={random_hex_color_code()} variation="solid" />
<Icon.CalendarPlus size="40" color={random_hex_color_code()} variation="solid" />
<Icon.CalendarTick size="40" color={random_hex_color_code()} variation="solid" />
<Icon.CalendarX size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Camera size="40" color={random_hex_color_code()} variation="solid" />
<Icon.CandleChart size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Car size="40" color={random_hex_color_code()} variation="solid" />
<Icon.CaretVertical size="40" color={random_hex_color_code()} variation="solid" />
<Icon.CaretVerticalCircle size="40" color={random_hex_color_code()} variation="solid" />
<Icon.CaretVerticalSmall size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Cart size="40" color={random_hex_color_code()} variation="solid" />
<Icon.CartMinus size="40" color={random_hex_color_code()} variation="solid" />
<Icon.CartPlus size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Certificate size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Chat size="40" color={random_hex_color_code()} variation="solid" />
<Icon.ChatTyping size="40" color={random_hex_color_code()} variation="solid" />
<Icon.ChatTypingAlt size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Chatbot size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Chrome size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Church size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Circle size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Clipboard size="40" color={random_hex_color_code()} variation="solid" />
<Icon.ClipboardMinus size="40" color={random_hex_color_code()} variation="solid" />
<Icon.ClipboardNoAccess size="40" color={random_hex_color_code()} variation="solid" />
<Icon.ClipboardPlus size="40" color={random_hex_color_code()} variation="solid" />
<Icon.ClipboardTick size="40" color={random_hex_color_code()} variation="solid" />
<Icon.ClipboardX size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Clock size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Clockwise size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Code size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Codepen size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Cog size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Compass size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Computer size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Contact size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Contract size="40" color={random_hex_color_code()} variation="solid" />
<Icon.CostEstimate size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Cplusplus size="40" color={random_hex_color_code()} variation="solid" />
<Icon.CreditCard size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Crop size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Css3 size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Csv size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Cup size="40" color={random_hex_color_code()} variation="solid" />
<Icon.CurvedConnector size="40" color={random_hex_color_code()} variation="solid" />
<Icon.D3 size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Database size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Denied size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Deno size="40" color={random_hex_color_code()} variation="solid" />
<Icon.DepthChart size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Desklamp size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Diamond size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Direction size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Discord size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Discount size="40" color={random_hex_color_code()} variation="solid" />
<Icon.DistributeHorizontal size="40" color={random_hex_color_code()} variation="solid" />
<Icon.DistributeVertical size="40" color={random_hex_color_code()} variation="solid" />
<Icon.DividerLine size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Doc size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Docker size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Documents size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Dollar size="40" color={random_hex_color_code()} variation="solid" />
<Icon.DonutChart size="40" color={random_hex_color_code()} variation="solid" />
<Icon.DoubleCaretDown size="40" color={random_hex_color_code()} variation="solid" />
<Icon.DoubleCaretDownCircle size="40" color={random_hex_color_code()} variation="solid" />
<Icon.DoubleCaretDownSmall size="40" color={random_hex_color_code()} variation="solid" />
<Icon.DoubleCaretLeft size="40" color={random_hex_color_code()} variation="solid" />
<Icon.DoubleCaretLeftCircle size="40" color={random_hex_color_code()} variation="solid" />
<Icon.DoubleCaretLeftSmall size="40" color={random_hex_color_code()} variation="solid" />
<Icon.DoubleCaretRight size="40" color={random_hex_color_code()} variation="solid" />
<Icon.DoubleCaretRightCircle size="40" color={random_hex_color_code()} variation="solid" />
<Icon.DoubleCaretRightSmall size="40" color={random_hex_color_code()} variation="solid" />
<Icon.DoubleCaretUp size="40" color={random_hex_color_code()} variation="solid" />
<Icon.DoubleCaretUpCircle size="40" color={random_hex_color_code()} variation="solid" />
<Icon.DoubleCaretUpSmall size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Down size="40" color={random_hex_color_code()} variation="solid" />
<Icon.DownCircle size="40" color={random_hex_color_code()} variation="solid" />
<Icon.DownSmall size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Download size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Drag size="40" color={random_hex_color_code()} variation="solid" />
<Icon.DragHorizontal size="40" color={random_hex_color_code()} variation="solid" />
<Icon.DragVertical size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Dribbble size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Drop size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Dropper size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Edge size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Edit size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Edit1 size="40" color={random_hex_color_code()} variation="solid" />
<Icon.EditCircle size="40" color={random_hex_color_code()} variation="solid" />
<Icon.EditSmall size="40" color={random_hex_color_code()} variation="solid" />
<Icon.ElbowConnector size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Envelope size="40" color={random_hex_color_code()} variation="solid" />
<Icon.EnvelopeOpen size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Eps size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Eslint size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Ethereum size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Euro size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Exclamation size="40" color={random_hex_color_code()} variation="solid" />
<Icon.ExclamationCircle size="40" color={random_hex_color_code()} variation="solid" />
<Icon.ExclamationSmall size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Expand size="40" color={random_hex_color_code()} variation="solid" />
<Icon.ExpandAlt size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Eye size="40" color={random_hex_color_code()} variation="solid" />
<Icon.EyeClosed size="40" color={random_hex_color_code()} variation="solid" />
<Icon.FaceId size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Facebook size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Figma size="40" color={random_hex_color_code()} variation="solid" />
<Icon.File size="40" color={random_hex_color_code()} variation="solid" />
<Icon.FileMinus size="40" color={random_hex_color_code()} variation="solid" />
<Icon.FileNoAccess size="40" color={random_hex_color_code()} variation="solid" />
<Icon.FilePlus size="40" color={random_hex_color_code()} variation="solid" />
<Icon.FileTick size="40" color={random_hex_color_code()} variation="solid" />
<Icon.FileX size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Filter size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Fingerprint size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Firebase size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Flag size="40" color={random_hex_color_code()} variation="solid" />
<Icon.FlagAlt size="40" color={random_hex_color_code()} variation="solid" />
<Icon.FlipHorizontal size="40" color={random_hex_color_code()} variation="solid" />
<Icon.FlipVertical size="40" color={random_hex_color_code()} variation="solid" />
<Icon.FloatCenter size="40" color={random_hex_color_code()} variation="solid" />
<Icon.FloatLeft size="40" color={random_hex_color_code()} variation="solid" />
<Icon.FloatRight size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Floorplan size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Folder size="40" color={random_hex_color_code()} variation="solid" />
<Icon.FolderMinus size="40" color={random_hex_color_code()} variation="solid" />
<Icon.FolderNoAccess size="40" color={random_hex_color_code()} variation="solid" />
<Icon.FolderPlus size="40" color={random_hex_color_code()} variation="solid" />
<Icon.FolderTick size="40" color={random_hex_color_code()} variation="solid" />
<Icon.FolderX size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Folders size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Forward size="40" color={random_hex_color_code()} variation="solid" />
<Icon.ForwardCircle size="40" color={random_hex_color_code()} variation="solid" />
<Icon.ForwardSmall size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Frame size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Framer size="40" color={random_hex_color_code()} variation="solid" />
<Icon.GameController size="40" color={random_hex_color_code()} variation="solid" />
<Icon.GameControllerRetro size="40" color={random_hex_color_code()} variation="solid" />
<Icon.GanttChart size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Garage size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Gatsbyjs size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Gba size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Gbc size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Ghost size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Gif size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Gift size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Git size="40" color={random_hex_color_code()} variation="solid" />
<Icon.GitBranch size="40" color={random_hex_color_code()} variation="solid" />
<Icon.GitCommit size="40" color={random_hex_color_code()} variation="solid" />
<Icon.GitCompare size="40" color={random_hex_color_code()} variation="solid" />
<Icon.GitFork size="40" color={random_hex_color_code()} variation="solid" />
<Icon.GitMerge size="40" color={random_hex_color_code()} variation="solid" />
<Icon.GitPull size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Github size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Gitlab size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Globe size="40" color={random_hex_color_code()} variation="solid" />
<Icon.GlobeAfrica size="40" color={random_hex_color_code()} variation="solid" />
<Icon.GlobeAmericas size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Google size="40" color={random_hex_color_code()} variation="solid" />
<Icon.GoogleAd size="40" color={random_hex_color_code()} variation="solid" />
<Icon.GoogleDrive size="40" color={random_hex_color_code()} variation="solid" />
<Icon.GooglePlayStore size="40" color={random_hex_color_code()} variation="solid" />
<Icon.GoogleStreetview size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Graphql size="40" color={random_hex_color_code()} variation="solid" />
<Icon.GridLayout size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Hashtag size="40" color={random_hex_color_code()} variation="solid" />
<Icon.HdScreen size="40" color={random_hex_color_code()} variation="solid" />
<Icon.HdmiCable size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Headphones size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Headset size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Heart size="40" color={random_hex_color_code()} variation="solid" />
<Icon.HeartCircle size="40" color={random_hex_color_code()} variation="solid" />
<Icon.HeartSmall size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Hexagon size="40" color={random_hex_color_code()} variation="solid" />
<Icon.History size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Home size="40" color={random_hex_color_code()} variation="solid" />
<Icon.HomeAlt size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Hospital size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Hourglass size="40" color={random_hex_color_code()} variation="solid" />
<Icon.House size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Html5 size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Id size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Imac size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Image size="40" color={random_hex_color_code()} variation="solid" />
<Icon.ImageAlt size="40" color={random_hex_color_code()} variation="solid" />
<Icon.ImageDocument size="40" color={random_hex_color_code()} variation="solid" />
<Icon.InEarHeadphones size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Inbox size="40" color={random_hex_color_code()} variation="solid" />
<Icon.IndentDecrease size="40" color={random_hex_color_code()} variation="solid" />
<Icon.IndentIncrease size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Info size="40" color={random_hex_color_code()} variation="solid" />
<Icon.InfoCircle size="40" color={random_hex_color_code()} variation="solid" />
<Icon.InfoSmall size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Instagram size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Invoice size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Italic size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Javascript size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Joystick size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Jpg size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Kanban size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Key size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Keyboard size="40" color={random_hex_color_code()} variation="solid" />
<Icon.LanCable size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Laptop size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Laravel size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Layers size="40" color={random_hex_color_code()} variation="solid" />
<Icon.LayersDifference size="40" color={random_hex_color_code()} variation="solid" />
<Icon.LayersIntersect size="40" color={random_hex_color_code()} variation="solid" />
<Icon.LayersSubtract size="40" color={random_hex_color_code()} variation="solid" />
<Icon.LayersUnion size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Left size="40" color={random_hex_color_code()} variation="solid" />
<Icon.LeftCircle size="40" color={random_hex_color_code()} variation="solid" />
<Icon.LeftSmall size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Lego size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Lifebuoy size="40" color={random_hex_color_code()} variation="solid" />
<Icon.LightningCable size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Line size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Link size="40" color={random_hex_color_code()} variation="solid" />
<Icon.LinkRemove size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Linkedin size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Linux size="40" color={random_hex_color_code()} variation="solid" />
<Icon.LinuxAlt size="40" color={random_hex_color_code()} variation="solid" />
<Icon.ListLayout size="40" color={random_hex_color_code()} variation="solid" />
<Icon.ListOrdered size="40" color={random_hex_color_code()} variation="solid" />
<Icon.ListUnordered size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Litecoin size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Loader size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Location size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Lock size="40" color={random_hex_color_code()} variation="solid" />
<Icon.LockCircle size="40" color={random_hex_color_code()} variation="solid" />
<Icon.LockSmall size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Logout size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Loop size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Magsafe size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Markdown size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Medium size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Menu size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Message size="40" color={random_hex_color_code()} variation="solid" />
<Icon.MessageMinus size="40" color={random_hex_color_code()} variation="solid" />
<Icon.MessageNoAccess size="40" color={random_hex_color_code()} variation="solid" />
<Icon.MessagePlus size="40" color={random_hex_color_code()} variation="solid" />
<Icon.MessageText size="40" color={random_hex_color_code()} variation="solid" />
<Icon.MessageTextAlt size="40" color={random_hex_color_code()} variation="solid" />
<Icon.MessageTick size="40" color={random_hex_color_code()} variation="solid" />
<Icon.MessageX size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Messenger size="40" color={random_hex_color_code()} variation="solid" />
<Icon.MicroSdCard size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Microphone size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Minimise size="40" color={random_hex_color_code()} variation="solid" />
<Icon.MinimiseAlt size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Minus size="40" color={random_hex_color_code()} variation="solid" />
<Icon.MinusCircle size="40" color={random_hex_color_code()} variation="solid" />
<Icon.MinusSmall size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Mobile size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Money size="40" color={random_hex_color_code()} variation="solid" />
<Icon.MoneyStack size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Mongodb size="40" color={random_hex_color_code()} variation="solid" />
<Icon.MoodFlat size="40" color={random_hex_color_code()} variation="solid" />
<Icon.MoodFrown size="40" color={random_hex_color_code()} variation="solid" />
<Icon.MoodLaugh size="40" color={random_hex_color_code()} variation="solid" />
<Icon.MoodSad size="40" color={random_hex_color_code()} variation="solid" />
<Icon.MoodSmile size="40" color={random_hex_color_code()} variation="solid" />
<Icon.MoodSurprised size="40" color={random_hex_color_code()} variation="solid" />
<Icon.MoodTongue size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Moon size="40" color={random_hex_color_code()} variation="solid" />
<Icon.MoreHorizontal size="40" color={random_hex_color_code()} variation="solid" />
<Icon.MoreVertical size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Mouse size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Mov size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Mp3 size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Mp4 size="40" color={random_hex_color_code()} variation="solid" />
<Icon.MsExcel size="40" color={random_hex_color_code()} variation="solid" />
<Icon.MsPowerpoint size="40" color={random_hex_color_code()} variation="solid" />
<Icon.MsWord size="40" color={random_hex_color_code()} variation="solid" />
<Icon.N64 size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Nes size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Netlify size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Next size="40" color={random_hex_color_code()} variation="solid" />
<Icon.NextCircle size="40" color={random_hex_color_code()} variation="solid" />
<Icon.NextSmall size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Nextjs size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Ngc size="40" color={random_hex_color_code()} variation="solid" />
<Icon.NintendoSwitch size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Nodejs size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Note size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Npm size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Nuxtjs size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Omega size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Opera size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Otp size="40" color={random_hex_color_code()} variation="solid" />
<Icon.PageBreak size="40" color={random_hex_color_code()} variation="solid" />
<Icon.PageNumber size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Paintbrush size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Paintbucket size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Paragraph size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Password size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Patreon size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Pause size="40" color={random_hex_color_code()} variation="solid" />
<Icon.PauseCircle size="40" color={random_hex_color_code()} variation="solid" />
<Icon.PauseSmall size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Paw size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Paws size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Paypal size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Pdf size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Pen size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Phone size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Phonecall size="40" color={random_hex_color_code()} variation="solid" />
<Icon.PhonecallBlocked size="40" color={random_hex_color_code()} variation="solid" />
<Icon.PhonecallReceive size="40" color={random_hex_color_code()} variation="solid" />
<Icon.PieChart size="40" color={random_hex_color_code()} variation="solid" />
<Icon.PieChartAlt size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Pin size="40" color={random_hex_color_code()} variation="solid" />
<Icon.PinAlt size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Pinterest size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Plant size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Play size="40" color={random_hex_color_code()} variation="solid" />
<Icon.PlayCircle size="40" color={random_hex_color_code()} variation="solid" />
<Icon.PlaySmall size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Plug size="40" color={random_hex_color_code()} variation="solid" />
<Icon.PlusCircle size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Png size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Pool size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Pound size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Power size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Ppt size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Print size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Python size="40" color={random_hex_color_code()} variation="solid" />
<Icon.QrCode size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Question size="40" color={random_hex_color_code()} variation="solid" />
<Icon.QuestionCircle size="40" color={random_hex_color_code()} variation="solid" />
<Icon.QuestionSmall size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Quote size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Rand size="40" color={random_hex_color_code()} variation="solid" />
<Icon.React size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Receipt size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Reddit size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Redwoodjs size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Refresh size="40" color={random_hex_color_code()} variation="solid" />
<Icon.RefreshAlt size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Rewind size="40" color={random_hex_color_code()} variation="solid" />
<Icon.RewindCircle size="40" color={random_hex_color_code()} variation="solid" />
<Icon.RewindSmall size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Right size="40" color={random_hex_color_code()} variation="solid" />
<Icon.RightCircle size="40" color={random_hex_color_code()} variation="solid" />
<Icon.RightSmall size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Ripple size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Robot size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Roller size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Rollupjs size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Router size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Rss size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Ruby size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Rupee size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Rust size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Safari size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Safe size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Save size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Scan size="40" color={random_hex_color_code()} variation="solid" />
<Icon.School size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Screen size="40" color={random_hex_color_code()} variation="solid" />
<Icon.ScreenAlt size="40" color={random_hex_color_code()} variation="solid" />
<Icon.ScreenAlt2 size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Scribble size="40" color={random_hex_color_code()} variation="solid" />
<Icon.SdCard size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Search size="40" color={random_hex_color_code()} variation="solid" />
<Icon.SearchCircle size="40" color={random_hex_color_code()} variation="solid" />
<Icon.SearchProperty size="40" color={random_hex_color_code()} variation="solid" />
<Icon.SearchSmall size="40" color={random_hex_color_code()} variation="solid" />
<Icon.SectionAdd size="40" color={random_hex_color_code()} variation="solid" />
<Icon.SectionRemove size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Send size="40" color={random_hex_color_code()} variation="solid" />
<Icon.SendDown size="40" color={random_hex_color_code()} variation="solid" />
<Icon.SendLeft size="40" color={random_hex_color_code()} variation="solid" />
<Icon.SendRight size="40" color={random_hex_color_code()} variation="solid" />
<Icon.SendUp size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Servers size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Share size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Shield size="40" color={random_hex_color_code()} variation="solid" />
<Icon.ShieldTick size="40" color={random_hex_color_code()} variation="solid" />
<Icon.ShieldX size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Shop size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Sign size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Signin size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Sim size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Simohamed size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Skull size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Skype size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Slack size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Snapchat size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Snes size="40" color={random_hex_color_code()} variation="solid" />
<Icon.SortAlphabetically size="40" color={random_hex_color_code()} variation="solid" />
<Icon.SortDown size="40" color={random_hex_color_code()} variation="solid" />
<Icon.SortHighToLow size="40" color={random_hex_color_code()} variation="solid" />
<Icon.SortLowToHigh size="40" color={random_hex_color_code()} variation="solid" />
<Icon.SortReverseAlphabetically size="40" color={random_hex_color_code()} variation="solid" />
<Icon.SortUp size="40" color={random_hex_color_code()} variation="solid" />
<Icon.SoundOff size="40" color={random_hex_color_code()} variation="solid" />
<Icon.SoundOn size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Spotify size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Spreadsheet size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Square size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Stackoverflow size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Stamp size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Star size="40" color={random_hex_color_code()} variation="solid" />
<Icon.StarCircle size="40" color={random_hex_color_code()} variation="solid" />
<Icon.StarSmall size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Stop size="40" color={random_hex_color_code()} variation="solid" />
<Icon.StopCircle size="40" color={random_hex_color_code()} variation="solid" />
<Icon.StopSmall size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Stopwatch size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Strikethrough size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Subscript size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Sun size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Superscript size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Svelte size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Svg size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Table size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Tablet size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Tag size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Tailwind size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Target size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Telegram size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Terminal size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Text size="40" color={random_hex_color_code()} variation="solid" />
<Icon.TextDocument size="40" color={random_hex_color_code()} variation="solid" />
<Icon.TextDocumentAlt size="40" color={random_hex_color_code()} variation="solid" />
<Icon.ThumbDown size="40" color={random_hex_color_code()} variation="solid" />
<Icon.ThumbUp size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Thumbtack size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Tick size="40" color={random_hex_color_code()} variation="solid" />
<Icon.TickCircle size="40" color={random_hex_color_code()} variation="solid" />
<Icon.TickSmall size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Tiktok size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Toggle size="40" color={random_hex_color_code()} variation="solid" />
<Icon.TopLeft size="40" color={random_hex_color_code()} variation="solid" />
<Icon.TopRight size="40" color={random_hex_color_code()} variation="solid" />
<Icon.TrendDown size="40" color={random_hex_color_code()} variation="solid" />
<Icon.TrendUp size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Triangle size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Trophy size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Tv size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Twitch size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Twitter size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Typescript size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Underline size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Unlock size="40" color={random_hex_color_code()} variation="solid" />
<Icon.UnlockCircle size="40" color={random_hex_color_code()} variation="solid" />
<Icon.UnlockSmall size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Up size="40" color={random_hex_color_code()} variation="solid" />
<Icon.UpCircle size="40" color={random_hex_color_code()} variation="solid" />
<Icon.UpSmall size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Upload size="40" color={random_hex_color_code()} variation="solid" />
<Icon.UsbCable size="40" color={random_hex_color_code()} variation="solid" />
<Icon.User size="40" color={random_hex_color_code()} variation="solid" />
<Icon.UserCircle size="40" color={random_hex_color_code()} variation="solid" />
<Icon.UserMinus size="40" color={random_hex_color_code()} variation="solid" />
<Icon.UserPlus size="40" color={random_hex_color_code()} variation="solid" />
<Icon.UserSquare size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Users size="40" color={random_hex_color_code()} variation="solid" />
<Icon.VectorDocument size="40" color={random_hex_color_code()} variation="solid" />
<Icon.VennDiagram size="40" color={random_hex_color_code()} variation="solid" />
<Icon.ViewColumn size="40" color={random_hex_color_code()} variation="solid" />
<Icon.ViewGrid size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Vim size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Volume1 size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Volume2 size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Volume3 size="40" color={random_hex_color_code()} variation="solid" />
<Icon.VrHeadset size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Vue size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Wallet size="40" color={random_hex_color_code()} variation="solid" />
<Icon.WalletAlt size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Wan size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Wand size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Watch size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Webpack size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Whatsapp size="40" color={random_hex_color_code()} variation="solid" />
<Icon.WifiFull size="40" color={random_hex_color_code()} variation="solid" />
<Icon.WifiLow size="40" color={random_hex_color_code()} variation="solid" />
<Icon.WifiNone size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Windows size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Wordpress size="40" color={random_hex_color_code()} variation="solid" />
<Icon.X size="40" color={random_hex_color_code()} variation="solid" />
<Icon.XCircle size="40" color={random_hex_color_code()} variation="solid" />
<Icon.XSmall size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Xls size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Yen size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Youtube size="40" color={random_hex_color_code()} variation="solid" />
<Icon.Zip size="40" color={random_hex_color_code()} variation="solid" />
<Icon.ZoomIn size="40" color={random_hex_color_code()} variation="solid" />
<Icon.ZoomOut size="40" color={random_hex_color_code()} variation="solid" />
